# Generated by Django 4.0.5 on 2022-07-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
