# Generated by Django 4.0.5 on 2022-06-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_person_photo_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='persons',
            field=models.ManyToManyField(blank=True, to='album.person'),
        ),
    ]
