# Generated by Django 4.0.5 on 2022-07-31 16:10

import album.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=album.utils.user_directory_path),
        ),
    ]
