# Generated by Django 4.0.5 on 2022-08-04 22:52

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='geomfield',
            field=djgeojson.fields.GeometryField(blank=True, null=True),
        ),
    ]
