# Generated by Django 4.0.5 on 2022-08-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_photo_geomfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='geomfield',
        ),
    ]
