# Generated by Django 4.2 on 2023-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='albums_user', to='album.album'),
        ),
    ]
