# Generated by Django 4.2 on 2024-05-31 04:54

import album.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_user_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contracted_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=album.utils.album_directory_path),
        ),
    ]
