# Generated by Django 4.2 on 2024-07-05 09:08

import album.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_user_contracted_size_user_paid_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='resized_image',
            field=models.ImageField(blank=True, null=True, upload_to=album.utils.resized_directory_path),
        ),
    ]
