# Generated by Django 4.2 on 2024-07-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_photo_resized_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='resized_image',
        ),
    ]
