# Generated by Django 4.2 on 2024-07-05 10:05

import album.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_remove_photo_resized_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='resized_image',
            field=models.ImageField(blank=True, null=True, upload_to=album.utils.resized_directory_path),
        ),
    ]
