# Generated by Django 4.2 on 2024-07-15 11:15

import album.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0016_remove_photo_resized_image_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=album.utils.resized_directory_path),
        ),
    ]
